Repository igorkulman/iOSLocalizationEditor, pull requests merged in 2019-03, with the labels that each got.

#33 Deleting translations
  LocalizationEditor.xcodeproj/project.pbxproj
  LocalizationEditor/Providers/LocalizationProvider.swift
  LocalizationEditor/Providers/LocalizationsDataSource.swift
  LocalizationEditor/UI/Cells/ActionsCell.swift
  LocalizationEditor/UI/Cells/ActionsCell.xib
  LocalizationEditor/UI/Cells/KeyCell.swift
  LocalizationEditor/UI/ViewController.swift
  editor.png
Labels: enhancement

#34 New UI using Toolbar
  README.md
  editor.png
  screenshots/editor.png
  sources/.swiftlint.yml
  sources/LocalizationEditor.xcodeproj/project.pbxproj
  sources/LocalizationEditor.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  sources/LocalizationEditor.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  sources/LocalizationEditor/AppDelegate.swift
  sources/LocalizationEditor/Assets.xcassets/AppIcon.appiconset/Contents.json
  sources/LocalizationEditor/Assets.xcassets/AppIcon.appiconset/icon128.png
  sources/LocalizationEditor/Assets.xcassets/AppIcon.appiconset/icon16.png
  sources/LocalizationEditor/Assets.xcassets/AppIcon.appiconset/icon256-1.png
  sources/LocalizationEditor/Assets.xcassets/AppIcon.appiconset/icon256.png
  sources/LocalizationEditor/Assets.xcassets/AppIcon.appiconset/icon32-1.png
  sources/LocalizationEditor/Assets.xcassets/AppIcon.appiconset/icon32.png
  sources/LocalizationEditor/Assets.xcassets/AppIcon.appiconset/icon64.png
  sources/LocalizationEditor/Assets.xcassets/Contents.json
  sources/LocalizationEditor/Controls/EditableNSTextField.swift
  sources/LocalizationEditor/Extensions/FileManager+Extension.swift
  sources/LocalizationEditor/Extensions/NSTableView+Click.swift
  sources/LocalizationEditor/Extensions/String+Extensions.swift
  sources/LocalizationEditor/Info.plist
  sources/LocalizationEditor/LocalizationEditor.entitlements
  sources/LocalizationEditor/Models/Localization.swift
  sources/LocalizationEditor/Models/LocalizationGroup.swift
  sources/LocalizationEditor/Models/LocalizationString.swift
  sources/LocalizationEditor/Providers/LocalizationProvider.swift
  sources/LocalizationEditor/Providers/LocalizationsDataSource.swift
  sources/LocalizationEditor/Providers/Parser.swift
  sources/LocalizationEditor/Providers/ParserTypes.swift
  sources/LocalizationEditor/UI/Base.lproj/Main.storyboard
  sources/LocalizationEditor/UI/Cells/ActionsCell.swift
  sources/LocalizationEditor/UI/Cells/ActionsCell.xib
  sources/LocalizationEditor/UI/Cells/KeyCell.swift
  sources/LocalizationEditor/UI/Cells/KeyCell.xib
  sources/LocalizationEditor/UI/Cells/LocalizationCell.swift
  sources/LocalizationEditor/UI/Cells/LocalizationCell.xib
  sources/LocalizationEditor/UI/ViewController.swift
  sources/LocalizationEditor/UI/WindowController.swift
  sources/LocalizationEditorTests/Data/InfoPList-en.strings
  sources/LocalizationEditorTests/Data/InfoPList-sk.strings
  sources/LocalizationEditorTests/Data/LocalizableStrings-en-with-complete-messages.strings
  sources/LocalizationEditorTests/Data/LocalizableStrings-en-with-incomplete-messages.strings
  sources/LocalizationEditorTests/Data/LocalizableStrings-en.strings
  sources/LocalizationEditorTests/Data/LocalizableStrings-sk-missing.strings
  sources/LocalizationEditorTests/Data/LocalizableStrings-sk.strings
  sources/LocalizationEditorTests/Extensions/XCTestCase+Extensions.swift
  sources/LocalizationEditorTests/Info.plist
  sources/LocalizationEditorTests/LoalizationProviderUpdatingTests.swift
  sources/LocalizationEditorTests/LocalizationProviderDeletingTests.swift
  sources/LocalizationEditorTests/LocalizationProviderParsingTests.swift
  sources/LocalizationEditorTests/ParserIsolationTests.swift
  sources/LocalizationEditorTests/TestFile.swift
Labels: enhancement

#38 Fixes #36 and fixes #37
  sources/LocalizationEditor/UI/ViewController.swift
Labels: bug

#40 Better way to convert language codes to flags
  sources/LocalizationEditor.xcodeproj/project.pbxproj
  sources/LocalizationEditor/Models/Flag.swift
  sources/LocalizationEditor/UI/ViewController.swift
Labels: enhancement

#41 Single line comments support
  sources/LocalizationEditor/Providers/Parser.swift
  sources/LocalizationEditor/Providers/ParserTypes.swift
  sources/LocalizationEditorTests/ParserIsolationTests.swift
Labels: bug, enhancement

#43 Menu improvements
  sources/LocalizationEditor.xcodeproj/project.pbxproj
  sources/LocalizationEditor/Controls/EditableNSTextField.swift
  sources/LocalizationEditor/UI/Base.lproj/Main.storyboard
  sources/LocalizationEditor/UI/Cells/LocalizationCell.xib
Labels: enhancement

#44 Faster and more robust single line comments handling
  sources/LocalizationEditor/Providers/Parser.swift
  sources/LocalizationEditor/Providers/ParserTypes.swift
  sources/LocalizationEditorTests/Data/LocalizableStrings-en-with-complete-messages.strings
Labels: enhancement

#47 Quotes fix
  sources/LocalizationEditor.xcodeproj/project.pbxproj
  sources/LocalizationEditor/Providers/Parser.swift
  sources/LocalizationEditorTests/Data/Special.strings
  sources/LocalizationEditorTests/LocalizationProviderParsingTests.swift
Labels: bug
